import Decimal from 'break_infinity.js'
import type { GameState } from './types'
import { TIER_CONFIGS, STARTING_SOUNDWAVES } from '../core/constants'
import { SAVE_SCHEMA_VERSION } from './saveSchema'

export function createInitialState(): GameState {
  return {
    soundwaves: new Decimal(STARTING_SOUNDWAVES),
    tiers: TIER_CONFIGS.map((config) => ({
      id: config.id,
      name: config.name,
      quantity: new Decimal(0),
      purchased: 0,
      multiplier: new Decimal(1),
      unlocked: config.id === 1,
    })),
    tempo: {
      level: 0,
      tickInterval: 1000,
      baseBPM: 60,
    },
    buyAmount: 1,
    achievements: [],
    completedChallenges: [],
    challengeBestTimes: {},
    keepChallenges: false,
    encoreUpgrades: {},
    autobuyers: {},
    activeChallenge: null,
    preChallengeState: null,
    encorePoints: 0,
    lifetimeEncorePoints: 0,
    encoreCount: 0,
    lifetimeEncoreCount: 0,
    applausePoints: 0,
    layer1WallReached: false,
    opusPoints: 0,
    opusCount: 0,
    opusUpgrades: {},
    crescendo: 0,
    peakCrescendoMult: 1,
    recordsSold: 0,
    platinum: false,
    acclaim: new Decimal(0),
    lifetimeAcclaim: new Decimal(0),
    tourCount: 0,
    currentVenue: 0,
    venueBuffer: new Decimal(0),
    venueSoldOut: false,
    components: {},
    catalogueSnapshot: new Decimal(1),
    worldTourUnlocked: false,
    autoCollect: false,
    keepAutobuyers: false,
    autoMO: false,
    autoMOEnabled: true,
    autoGraduate: false,
    autoTour: false,
    autoTourEnabled: true,
    circuitComplete: false,
    postPlatinumMoCount: 0,
    finalePoints: 0,
    finaleCount: 0,
    peakSoundwaves: new Decimal(0),
    producedThisRun: new Decimal(0),
    tempoPurchasesThisRun: 0,
    silentEncoresCompleted: 0,
    wallReachedWithoutTempo: false,
    wallReachedWithoutTempoAtActiveMs: 0,
    totalTimePlayed: 0,
    activeTimePlayed: 0,
    lastSaveTimestamp: Date.now(),
    currentRunStartTime: Date.now(),
    version: '0.6.0',
    saveSchemaVersion: SAVE_SCHEMA_VERSION,
    seenStoryBeats: [],
  }
}
