import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import Decimal from 'break_infinity.js'
import type { GameActions, GameState, TierState } from './types'
import {
  AUTOBUYER_DEFAULT_INTERVAL,
  GRAND_FINALE_SW_THRESHOLD,
  PLATINUM_THRESHOLD,
  getEncoreCost,
  getMagnumOpusCost,
} from '../core/constants'
import { getMilestoneMultiplier } from '../core/formulas'

const mem: Record<string, string> = {}
;(globalThis as unknown as { localStorage: Storage }).localStorage = {
  getItem: (k: string) => mem[k] ?? null,
  setItem: (k: string, v: string) => { mem[k] = v },
  removeItem: (k: string) => { delete mem[k] },
  clear: () => { for (const k of Object.keys(mem)) delete mem[k] },
  key: () => null,
  length: 0,
} as Storage

const { useGameStore } = await import('./gameStore')
const { createInitialState } = await import('./initialState')

const PINNED_NOW = 1_800_000_000_000
const RESET_ACTIONS = [
  'performEncore',
  'performMagnumOpus',
  'performTour',
  'performGrandFinale',
] as const satisfies readonly (keyof GameActions)[]

const PERK_ACHIEVEMENTS = [
  'ach_perk_skip_wall',
  'ach_perk_muscle_memory',
  'ach_perk_warmup',
  'ach_perk_tempo_headstart',
  'ach_perk_sustained_note',
  'ach_perk_second_wind',
]

const STATE_KEYS = [
  'soundwaves',
  'tiers',
  'tempo',
  'warmUpLevel',
  'activityGraceMs',
  'buyAmount',
  'achievements',
  'completedChallenges',
  'challengeBestTimes',
  'keepChallenges',
  'encoreUpgrades',
  'autobuyers',
  'activeChallenge',
  'preChallengeState',
  'encorePoints',
  'lifetimeEncorePoints',
  'encoreCount',
  'lifetimeEncoreCount',
  'applausePoints',
  'layer1WallReached',
  'opusPoints',
  'opusCount',
  'opusUpgrades',
  'crescendo',
  'peakCrescendoMult',
  'recordsSold',
  'platinum',
  'acclaim',
  'lifetimeAcclaim',
  'tourCount',
  'currentVenue',
  'venueBuffer',
  'venueSoldOut',
  'components',
  'catalogueSnapshot',
  'worldTourUnlocked',
  'autoCollect',
  'keepAutobuyers',
  'autoMO',
  'autoMOEnabled',
  'autoGraduate',
  'autoTour',
  'autoTourEnabled',
  'circuitComplete',
  'postPlatinumMoCount',
  'finalePoints',
  'finaleCount',
  'peakSoundwaves',
  'producedThisRun',
  'tempoPurchasesThisRun',
  'silentEncoresCompleted',
  'wallReachedWithoutTempo',
  'wallReachedWithoutTempoAtActiveMs',
  'totalTimePlayed',
  'activeTimePlayed',
  'lastSaveTimestamp',
  'currentRunStartTime',
  'version',
  'saveSchemaVersion',
  'seenStoryBeats',
  'seenHints',
] as const satisfies readonly (keyof GameState)[]

type ResetAction = typeof RESET_ACTIONS[number]

function normalize(value: unknown): unknown {
  if (value instanceof Decimal) return value.toString()
  if (Array.isArray(value)) return value.map(normalize)
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const key of Object.keys(value).sort()) {
      out[key] = normalize((value as Record<string, unknown>)[key])
    }
    return out
  }
  return value
}

function snapshotState(state: GameState): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const key of STATE_KEYS) {
    out[key] = normalize(state[key])
  }
  return out
}

function gateTiers(cost: { tierIndex: number; amount: number }): TierState[] {
  return createInitialState().tiers.map((tier, index) => {
    const purchased = index === cost.tierIndex ? cost.amount : 0
    return {
      ...tier,
      quantity: new Decimal(purchased),
      purchased,
      multiplier: purchased > 0 ? getMilestoneMultiplier(purchased) : new Decimal(1),
      unlocked: index <= cost.tierIndex,
    }
  })
}

function sampleAutobuyers(): GameState['autobuyers'] {
  return {
    tier_2: {
      unlocked: true,
      enabled: true,
      interval: AUTOBUYER_DEFAULT_INTERVAL,
      bulk: 10,
      lastTick: PINNED_NOW - 20_000,
    },
    encore: {
      unlocked: true,
      enabled: false,
      interval: AUTOBUYER_DEFAULT_INTERVAL,
      bulk: 1,
      lastTick: PINNED_NOW - 10_000,
    },
  }
}

function setScenario(overrides: Partial<GameState>): void {
  useGameStore.getState().hardReset()
  useGameStore.setState({
    soundwaves: new Decimal('9e45'),
    peakSoundwaves: new Decimal('1e30'),
    producedThisRun: new Decimal('5e29'),
    tempo: { level: 6, tickInterval: 625, baseBPM: 96 },
    tempoPurchasesThisRun: 4,
    currentRunStartTime: PINNED_NOW - 120_000,
    activityGraceMs: 1234,
    crescendo: 0.65,
    peakCrescendoMult: 4.25,
    encorePoints: 12,
    lifetimeEncorePoints: 34,
    encoreCount: 2,
    lifetimeEncoreCount: 11,
    applausePoints: 21,
    layer1WallReached: false,
    opusPoints: 5,
    opusCount: 2,
    opusUpgrades: { 'op-gain-flat': 2, 'tempo-op-mult': 1 },
    recordsSold: 750_000,
    platinum: false,
    acclaim: new Decimal('123.45'),
    lifetimeAcclaim: new Decimal('678.9'),
    tourCount: 1,
    currentVenue: 2,
    venueBuffer: new Decimal('8.5'),
    venueSoldOut: true,
    components: { posters: 2, lights: 1 },
    catalogueSnapshot: new Decimal('6.75'),
    worldTourUnlocked: true,
    autoCollect: true,
    keepAutobuyers: false,
    autoMO: true,
    autoMOEnabled: false,
    autoGraduate: true,
    autoTour: true,
    autoTourEnabled: false,
    circuitComplete: false,
    postPlatinumMoCount: 1,
    finalePoints: 2,
    finaleCount: 1,
    silentEncoresCompleted: 3,
    wallReachedWithoutTempo: false,
    wallReachedWithoutTempoAtActiveMs: 0,
    totalTimePlayed: 987_654,
    activeTimePlayed: 456_789,
    lastSaveTimestamp: PINNED_NOW - 1_000,
    seenStoryBeats: ['intro'],
    seenHints: ['buy-note'],
    ...overrides,
  })
}

function runReset(action: ResetAction, overrides: Partial<GameState>): Record<string, unknown> {
  setScenario(overrides)
  useGameStore.getState()[action]()
  return snapshotState(useGameStore.getState())
}

describe('reset action characterization', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(PINNED_NOW)
    localStorage.clear()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  describe('performEncore', () => {
    it('snapshots a plain at-gate mid-run', () => {
      expect(runReset('performEncore', {
        tiers: gateTiers(getEncoreCost(2)),
        worldTourUnlocked: false,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 12000,
          "applausePoints": 23,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.65,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 3,
          "encorePoints": 14,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": false,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 12,
          "lifetimeEncorePoints": 36,
          "opusCount": 2,
          "opusPoints": 5,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 4.25,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": false,
        }
      `)
    })

    it('snapshots perks with free second wind, warmup, crescendo, and sight-reading', () => {
      expect(runReset('performEncore', {
        achievements: PERK_ACHIEVEMENTS,
        encoreCount: 0,
        encoreUpgrades: { sightReading: 1, overture: 2, perfectPitch: 3 },
        tiers: gateTiers(getEncoreCost(0)),
        peakSoundwaves: new Decimal('1e24'),
        worldTourUnlocked: false,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [
            "ach_perk_skip_wall",
            "ach_perk_muscle_memory",
            "ach_perk_warmup",
            "ach_perk_tempo_headstart",
            "ach_perk_sustained_note",
            "ach_perk_second_wind",
          ],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 12000,
          "applausePoints": 22,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.4,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 1,
          "encorePoints": 13,
          "encoreUpgrades": {
            "overture": 2,
            "perfectPitch": 3,
            "sightReading": 1,
          },
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": false,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 12,
          "lifetimeEncorePoints": 35,
          "opusCount": 2,
          "opusPoints": 5,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 4.25,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "1000000000000",
          "tempo": {
            "baseBPM": 108,
            "level": 8,
            "tickInterval": 555.5555555555555,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "2",
              "name": "Notes",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "2",
              "name": "Motifs",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": false,
        }
      `)
    })

    it('snapshots the wall-count patron edge', () => {
      expect(runReset('performEncore', {
        encoreCount: 7,
        tiers: gateTiers(getEncoreCost(7)),
        currentRunStartTime: PINNED_NOW - 4 * 60_000,
        tempoPurchasesThisRun: 0,
        activeTimePlayed: 222_222,
        worldTourUnlocked: false,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 222222,
          "activityGraceMs": 12000,
          "applausePoints": 23,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.65,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 8,
          "encorePoints": 14,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 12,
          "lifetimeEncorePoints": 36,
          "opusCount": 2,
          "opusPoints": 5,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 4.25,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 4,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": true,
          "wallReachedWithoutTempoAtActiveMs": 222222,
          "warmUpLevel": 0,
          "worldTourUnlocked": false,
        }
      `)
    })
  })

  describe('performMagnumOpus', () => {
    it('snapshots a plain at-gate first opus', () => {
      expect(runReset('performMagnumOpus', {
        layer1WallReached: true,
        opusCount: 0,
        tiers: gateTiers(getMagnumOpusCost(0)),
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 12000,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {
            "tier_1": {
              "bulk": 1,
              "enabled": true,
              "interval": 500,
              "lastTick": 0,
              "unlocked": true,
            },
          },
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": false,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 1,
          "opusPoints": 8,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots perks with platinum and kept encore upgrades', () => {
      expect(runReset('performMagnumOpus', {
        achievements: PERK_ACHIEVEMENTS,
        layer1WallReached: true,
        tiers: gateTiers(getMagnumOpusCost(3)),
        opusCount: 3,
        opusPoints: 17,
        encoreUpgrades: { perfectPitch: 4, sightReading: 1 },
        opusUpgrades: { 'op-gain-flat': 3, 'crescendo-op-bonus': 2 },
        recordsSold: 1_500_000,
        platinum: true,
        autobuyers: sampleAutobuyers(),
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [
            "ach_perk_skip_wall",
            "ach_perk_muscle_memory",
            "ach_perk_warmup",
            "ach_perk_tempo_headstart",
            "ach_perk_sustained_note",
            "ach_perk_second_wind",
          ],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 12000,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {
            "encore": {
              "bulk": 1,
              "enabled": false,
              "interval": 500,
              "lastTick": 1799999990000,
              "unlocked": true,
            },
            "tier_2": {
              "bulk": 10,
              "enabled": true,
              "interval": 500,
              "lastTick": 1799999980000,
              "unlocked": true,
            },
          },
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.4,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {
            "perfectPitch": 4,
            "sightReading": 1,
          },
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 4,
          "opusPoints": 35,
          "opusUpgrades": {
            "crescendo-op-bonus": 2,
            "op-gain-flat": 3,
          },
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": true,
          "postPlatinumMoCount": 2,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 1500000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "510",
          "tempo": {
            "baseBPM": 108,
            "level": 8,
            "tickInterval": 555.5555555555555,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "2",
              "name": "Notes",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "2",
              "name": "Motifs",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots the post-platinum counter edge when records reached the threshold', () => {
      expect(runReset('performMagnumOpus', {
        layer1WallReached: true,
        tiers: gateTiers(getMagnumOpusCost(1)),
        opusCount: 1,
        recordsSold: PLATINUM_THRESHOLD,
        platinum: false,
        postPlatinumMoCount: 4,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 12000,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": false,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 2,
          "opusPoints": 8,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 5,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 1000000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })
  })

  describe('performTour', () => {
    it('snapshots a plain unlocked tour without Roadies', () => {
      expect(runReset('performTour', {
        worldTourUnlocked: true,
        keepAutobuyers: false,
        recordsSold: 900_000,
        platinum: false,
        autobuyers: sampleAutobuyers(),
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": false,
          "autoMOEnabled": true,
          "autoTour": false,
          "autoTourEnabled": true,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "2.5376",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 3,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 2,
          "opusPoints": 0,
          "opusUpgrades": {},
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 108000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 2,
          "venueBuffer": "0",
          "venueSoldOut": false,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots perks and Roadies preserving autobuyers and automation', () => {
      expect(runReset('performTour', {
        achievements: PERK_ACHIEVEMENTS,
        worldTourUnlocked: true,
        keepAutobuyers: true,
        recordsSold: 15_000_000,
        platinum: true,
        encoreUpgrades: { perfectPitch: 5, sightReading: 1 },
        autobuyers: sampleAutobuyers(),
        autoMO: true,
        autoMOEnabled: false,
        autoTour: true,
        autoTourEnabled: false,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [
            "ach_perk_skip_wall",
            "ach_perk_muscle_memory",
            "ach_perk_warmup",
            "ach_perk_tempo_headstart",
            "ach_perk_sustained_note",
            "ach_perk_second_wind",
          ],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {
            "encore": {
              "bulk": 1,
              "enabled": false,
              "interval": 500,
              "lastTick": 1799999990000,
              "unlocked": true,
            },
            "tier_2": {
              "bulk": 10,
              "enabled": true,
              "interval": 500,
              "lastTick": 1799999980000,
              "unlocked": true,
            },
          },
          "buyAmount": 1,
          "catalogueSnapshot": "6.26",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.4,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 3,
          "encorePoints": 0,
          "encoreUpgrades": {
            "perfectPitch": 5,
            "sightReading": 1,
          },
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": true,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 2,
          "opusPoints": 0,
          "opusUpgrades": {},
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": true,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 1800000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "510",
          "tempo": {
            "baseBPM": 108,
            "level": 8,
            "tickInterval": 555.5555555555555,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "2",
              "name": "Notes",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "2",
              "name": "Motifs",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 2,
          "venueBuffer": "0",
          "venueSoldOut": false,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots carried records re-deriving platinum without Roadies', () => {
      expect(runReset('performTour', {
        worldTourUnlocked: true,
        keepAutobuyers: false,
        recordsSold: 8_500_000,
        platinum: false,
        autobuyers: sampleAutobuyers(),
        autoMO: true,
        autoMOEnabled: true,
        autoTour: true,
        autoTourEnabled: true,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": false,
          "autoMOEnabled": true,
          "autoTour": false,
          "autoTourEnabled": true,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "4.5440000000000005",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 3,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 1,
          "finalePoints": 2,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 2,
          "opusPoints": 0,
          "opusUpgrades": {},
          "peakCrescendoMult": 1,
          "peakSoundwaves": "0",
          "platinum": true,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 1020000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 2,
          "venueBuffer": "0",
          "venueSoldOut": false,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })
  })

  describe('performGrandFinale', () => {
    it('snapshots a plain finale with current omitted fields populated', () => {
      expect(runReset('performGrandFinale', {
        layer1WallReached: true,
        soundwaves: GRAND_FINALE_SW_THRESHOLD,
        opusUpgrades: { 'op-gain-flat': 4, 'tempo-op-mult': 2 },
        peakCrescendoMult: 5.5,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.65,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 2,
          "finalePoints": 3,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 0,
          "opusPoints": 0,
          "opusUpgrades": {
            "op-gain-flat": 4,
            "tempo-op-mult": 2,
          },
          "peakCrescendoMult": 5.5,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots perks seeding warmup and crescendo on finale', () => {
      expect(runReset('performGrandFinale', {
        achievements: PERK_ACHIEVEMENTS,
        layer1WallReached: true,
        soundwaves: GRAND_FINALE_SW_THRESHOLD.times(2),
        encoreUpgrades: { perfectPitch: 4, sightReading: 1 },
        opusUpgrades: { 'op-gain-flat': 4, 'tempo-op-mult': 2 },
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [
            "ach_perk_skip_wall",
            "ach_perk_muscle_memory",
            "ach_perk_warmup",
            "ach_perk_tempo_headstart",
            "ach_perk_sustained_note",
            "ach_perk_second_wind",
          ],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.4,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 2,
          "finalePoints": 3,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 0,
          "opusPoints": 0,
          "opusUpgrades": {
            "op-gain-flat": 4,
            "tempo-op-mult": 2,
          },
          "peakCrescendoMult": 4.25,
          "peakSoundwaves": "0",
          "platinum": false,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 750000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "510",
          "tempo": {
            "baseBPM": 108,
            "level": 8,
            "tickInterval": 555.5555555555555,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "2",
              "name": "Notes",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "2",
              "name": "Motifs",
              "purchased": 10,
              "quantity": "10",
              "unlocked": true,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })

    it('snapshots the encore wall flag remaining true after finale', () => {
      expect(runReset('performGrandFinale', {
        layer1WallReached: true,
        soundwaves: GRAND_FINALE_SW_THRESHOLD.times(3),
        crescendo: 0.9,
        peakCrescendoMult: 6,
        recordsSold: 2_500_000,
        platinum: true,
      })).toMatchInlineSnapshot(`
        {
          "acclaim": "123.44999999999999",
          "achievements": [],
          "activeChallenge": null,
          "activeTimePlayed": 456789,
          "activityGraceMs": 1234,
          "applausePoints": 21,
          "autoCollect": true,
          "autoGraduate": true,
          "autoMO": true,
          "autoMOEnabled": false,
          "autoTour": true,
          "autoTourEnabled": false,
          "autobuyers": {},
          "buyAmount": 1,
          "catalogueSnapshot": "6.75",
          "challengeBestTimes": {},
          "circuitComplete": false,
          "completedChallenges": [],
          "components": {
            "lights": 1,
            "posters": 2,
          },
          "crescendo": 0.9,
          "currentRunStartTime": 1800000000000,
          "currentVenue": 2,
          "encoreCount": 0,
          "encorePoints": 0,
          "encoreUpgrades": {},
          "finaleCount": 2,
          "finalePoints": 3,
          "keepAutobuyers": false,
          "keepChallenges": false,
          "lastSaveTimestamp": 1799999999000,
          "layer1WallReached": true,
          "lifetimeAcclaim": "678.9",
          "lifetimeEncoreCount": 11,
          "lifetimeEncorePoints": 0,
          "opusCount": 0,
          "opusPoints": 0,
          "opusUpgrades": {
            "op-gain-flat": 2,
            "tempo-op-mult": 1,
          },
          "peakCrescendoMult": 6,
          "peakSoundwaves": "0",
          "platinum": true,
          "postPlatinumMoCount": 1,
          "preChallengeState": null,
          "producedThisRun": "0",
          "recordsSold": 2500000,
          "saveSchemaVersion": 4,
          "seenHints": [
            "buy-note",
          ],
          "seenStoryBeats": [
            "intro",
          ],
          "silentEncoresCompleted": 3,
          "soundwaves": "10",
          "tempo": {
            "baseBPM": 60,
            "level": 0,
            "tickInterval": 1000,
          },
          "tempoPurchasesThisRun": 0,
          "tiers": [
            {
              "id": 1,
              "multiplier": "1",
              "name": "Notes",
              "purchased": 0,
              "quantity": "0",
              "unlocked": true,
            },
            {
              "id": 2,
              "multiplier": "1",
              "name": "Motifs",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 3,
              "multiplier": "1",
              "name": "Phrases",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 4,
              "multiplier": "1",
              "name": "Melodies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 5,
              "multiplier": "1",
              "name": "Harmonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 6,
              "multiplier": "1",
              "name": "Movements",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
            {
              "id": 7,
              "multiplier": "1",
              "name": "Symphonies",
              "purchased": 0,
              "quantity": "0",
              "unlocked": false,
            },
          ],
          "totalTimePlayed": 987654,
          "tourCount": 1,
          "venueBuffer": "8.5",
          "venueSoldOut": true,
          "version": "0.6.0",
          "wallReachedWithoutTempo": false,
          "wallReachedWithoutTempoAtActiveMs": 0,
          "warmUpLevel": 0,
          "worldTourUnlocked": true,
        }
      `)
    })
  })
})
